server:
  port: 8060
spring:
  #连接数据库
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/sunny-reader-data-base?characterEncoding=UTF-8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  #session集群
  session:
    store-type: none

security:
  basic:
    enabled: false